/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addVillage`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landmarks`; params?: Router.UnknownInputParams; } | { pathname: `/location`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/SubmitUpdate`; params?: Router.UnknownInputParams; } | { pathname: `/EmergencyPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/AboutUs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ContactUs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/homepage`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/LandmarkForm`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/local`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/logout`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/village/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/addVillage`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/landmarks`; params?: Router.UnknownOutputParams; } | { pathname: `/location`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/SubmitUpdate`; params?: Router.UnknownOutputParams; } | { pathname: `/EmergencyPage`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/AboutUs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/ContactUs`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/homepage`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/LandmarkForm`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/local`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/logout`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/village/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/addVillage${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/landmarks${`?${string}` | `#${string}` | ''}` | `/location${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/SubmitUpdate${`?${string}` | `#${string}` | ''}` | `/EmergencyPage${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/tabs/AboutUs${`?${string}` | `#${string}` | ''}` | `/tabs/ContactUs${`?${string}` | `#${string}` | ''}` | `/tabs/homepage${`?${string}` | `#${string}` | ''}` | `/tabs/LandmarkForm${`?${string}` | `#${string}` | ''}` | `/tabs/local${`?${string}` | `#${string}` | ''}` | `/tabs/logout${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addVillage`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/landmarks`; params?: Router.UnknownInputParams; } | { pathname: `/location`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/SubmitUpdate`; params?: Router.UnknownInputParams; } | { pathname: `/EmergencyPage`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/AboutUs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/ContactUs`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/homepage`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/LandmarkForm`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/local`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/logout`; params?: Router.UnknownInputParams; } | `/+not-found` | `/village/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/village/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
