/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AboutUs` | `/AboutUs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ContactUs` | `/ContactUs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homepage` | `/homepage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/location` | `/location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapScreen` | `/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/showmap` | `/showmap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SubmitUpdate` | `/SubmitUpdate`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AboutUs` | `/AboutUs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ContactUs` | `/ContactUs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/homepage` | `/homepage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/location` | `/location`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/MapScreen` | `/MapScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/showmap` | `/showmap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SubmitUpdate` | `/SubmitUpdate`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AboutUs${`?${string}` | `#${string}` | ''}` | `/AboutUs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ContactUs${`?${string}` | `#${string}` | ''}` | `/ContactUs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/homepage${`?${string}` | `#${string}` | ''}` | `/homepage${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/location${`?${string}` | `#${string}` | ''}` | `/location${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/MapScreen${`?${string}` | `#${string}` | ''}` | `/MapScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/showmap${`?${string}` | `#${string}` | ''}` | `/showmap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SubmitUpdate${`?${string}` | `#${string}` | ''}` | `/SubmitUpdate${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AboutUs` | `/AboutUs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ContactUs` | `/ContactUs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/homepage` | `/homepage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/location` | `/location`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/MapScreen` | `/MapScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/showmap` | `/showmap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SubmitUpdate` | `/SubmitUpdate`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
